apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::445567082433:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-vhLwH3br1Sd8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::445567082433:user/manvi
      username: manvi
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-29T10:53:54Z"
  name: aws-auth
  namespace: kube-system
  uid: d07a7e74-2925-4b86-a7a3-e8d2db866de2
