apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-trainee
  namespace: default
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-trainee
  namespace: default
subjects:
- kind: User
  name: manvi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: default-trainee
  apiGroup: rbac.authorization.k8s.io